import React from 'react'
import ReactDOM from 'react-dom/client'
import { BrowserRouter } from 'react-router-dom'
import App from './App'
import './styles.css'
import './phase15.css'
import './phase15-responsive.css'
import './phase16-directory.css'
import './coming-soon.css'
import './compact-grid.css'
import './screenshot-fit.css'
import './screenshot-compact.css'
import './legal.css'
import './support.css'
import './detail-links.css'
import './contact-panel.css'
import './linkedin.css'

ReactDOM.createRoot(document.getElementById('root')).render(<BrowserRouter><App /></BrowserRouter>)
