import { ArrowUpRight } from 'lucide-react'

const sections = [
  ['1. Eligibility', 'You must be at least 13 years old, or the minimum age required in your jurisdiction, to use Priora. By using the Service, you represent that you have legal capacity to enter these Terms, the information you provide is accurate and current, and you will comply with applicable laws and regulations.'],
  ['2. Account Registration', 'To access certain features, you may be required to create an account. Provide accurate and complete information, maintain the security of your credentials, notify Priora of unauthorized access, and accept responsibility for activities under your account. You are responsible for safeguarding your password and account information.'],
  ['3. Email Verification', 'Certain accounts may require email verification before full access is granted. Priora may send verification codes or authentication emails, restrict features until verification, and suspend accounts using invalid or fraudulent email addresses.'],
  ['4. User Content', 'You retain ownership of the tasks, notes, goals, schedules, reminders, attachments, and other content you create. You grant Priora a limited, non-exclusive license to store, process, display, and transmit your content solely to operate, maintain, and improve the Service. You are responsible for submitted content and must not upload unlawful, infringing, malicious, abusive, fraudulent, deceptive, or illegal material.'],
  ['5. Acceptable Use', 'You agree not to attempt unauthorized access, reverse engineer or interfere with the Service, abuse automated tools, circumvent security, distribute malware, use the Service illegally or fraudulently, or impersonate another person or entity. Priora may suspend or terminate accounts that violate these Terms.'],
  ['6. Subscription and Paid Features', 'Priora is currently offered free of charge unless otherwise stated. Future paid features, subscriptions, premium plans, AI functionality, storage upgrades, or analytics tools may be introduced. Prices will be shown before purchase, billing may use third-party providers, subscriptions may renew unless canceled, taxes may apply, and payment-provider policies govern applicable refunds. Users will not be required to purchase future paid features to continue using available free features.'],
  ['7. Third-Party Services', 'Priora may integrate Google Authentication, Supabase, email delivery, cloud hosting, infrastructure, analytics, and processing services necessary to operate the Service. Their own terms and privacy policies may apply. Priora is not responsible for third-party services beyond its reasonable control.'],
  ['8. Data Storage and Availability', 'Priora strives to provide reliable service but does not guarantee uninterrupted availability. Interruptions, maintenance, third-party outages, and data loss may occur. Users are encouraged to maintain backups of important information.'],
  ['9. Intellectual Property', 'The Priora name, PriorApp branding, logos, software, design elements, interfaces, graphics, content, and related materials are owned by PriorApp and protected by law. Except as expressly permitted, you may not copy, modify, distribute, sell, license, reverse engineer, or commercially exploit the Service without written permission.'],
  ['10. Feedback', 'If you provide suggestions, ideas, feature requests, bug reports, feedback, or recommendations, you grant Priora the right to use that feedback without restriction, attribution, or compensation.'],
  ['11. Privacy', 'Your use of Priora is also governed by the Priora Privacy Policy, which explains how personal information is collected, processed, stored, protected, retained, and deleted.'],
  ['12. Security', 'Priora implements reasonable technical and organizational measures to protect accounts and information, but no system guarantees absolute security. Users must maintain strong passwords, protect devices, keep credentials confidential, and report suspected security incidents.'],
  ['13. Account Suspension and Termination', 'Priora may suspend or terminate accounts that violate these Terms, engage in abuse, fraud, or unlawful activity, threaten platform security, harm users or the Service, or create excessive operational or security risks. Users may discontinue use at any time. Termination may result in removal of associated account data where permitted by law.'],
  ['14. Account Deletion', 'Users may request account deletion by contacting priorahq@gmail.com. After verifying account ownership, Priora will make reasonable efforts to delete account information and associated data, subject to legal, security, operational, regulatory, auditing, backup, or fraud-prevention requirements.'],
  ['15. Disclaimer of Warranties', 'The Service is provided on an AS IS and AS AVAILABLE basis. To the fullest extent permitted by law, Priora disclaims warranties including merchantability, fitness for a particular purpose, non-infringement, availability, reliability, accuracy, and continuous operation.'],
  ['16. Limitation of Liability', 'To the maximum extent permitted by law, Priora, PriorApp, and its affiliates, officers, employees, contractors, operators, and partners are not liable for indirect, incidental, consequential, special damages, loss of profits, business opportunities, data, or business interruption arising from use of the Service. Where liability cannot be excluded, it is limited to amounts paid to Priora during the preceding twelve months, if any.'],
  ['17. Indemnification', 'You agree to indemnify and hold harmless Priora, PriorApp, its operators, affiliates, employees, contractors, and partners from claims, damages, losses, liabilities, costs, and expenses arising from your use of the Service, violation of these Terms or law, infringement of third-party rights, or content you upload, create, store, or distribute.'],
  ['18. Changes to the Service', 'Priora may modify, suspend, replace, restrict, or discontinue portions of the Service at any time and is not obligated to maintain specific features indefinitely.'],
  ['19. Changes to These Terms', 'Priora may update these Terms. Material changes may be communicated through the Service, website, email, or other reasonable means. Continued use after updates become effective constitutes acceptance of the revised Terms.'],
  ['20. Entire Agreement', 'These Terms, together with the Priora Privacy Policy and additional policies referenced within the Service, constitute the entire agreement between you and PriorApp regarding your use of Priora.'],
  ['21. Governing Law', 'These Terms are governed by and interpreted according to the laws of India. Disputes are subject to the exclusive jurisdiction of competent courts in India.'],
]

export default function PrioraTerms() {
  return <main><section className="directory-header policy-header"><div className="container"><span className="badge">Priora / Legal</span><h1>Terms of Service for Priora.</h1><p>Effective September 3, 2026 · Last updated September 3, 2026</p></div></section><section className="section compact-section policy-content"><div className="container narrow"><p className="policy-lead">Welcome to Priora. These Terms of Service govern your access to and use of the Priora mobile application, website, and related services. Priora is operated by PriorApp. By creating an account, accessing, or using Priora, you agree to these Terms.</p>{sections.map(([title, body]) => <section className="policy-block" key={title}><h2>{title}</h2><p>{body}</p></section>)}<section className="policy-block"><h2>22. Contact Information</h2><p>For questions regarding these Terms, contact PriorApp at <a className="policy-link" href="mailto:priorahq@gmail.com">priorahq@gmail.com <ArrowUpRight size={14} /></a>.</p><p>Website: <a className="policy-link" href="https://priorapp.co.in/">priorapp.co.in <ArrowUpRight size={14} /></a></p><p>Terms of Service URL: <a className="policy-link" href="https://priorapp.co.in/terms/priora">priorapp.co.in/terms/priora <ArrowUpRight size={14} /></a></p><p>By using Priora, you acknowledge that you have read, understood, and agreed to these Terms of Service.</p></section></div></section></main>
}
