import { ArrowUpRight } from 'lucide-react'

const sections = [
  ['1. Introduction', 'Priora is a productivity platform designed to help users manage tasks, goals, milestones, schedules, reminders, focus sessions, and related productivity workflows. By using Priora, you agree to the collection and use of information in accordance with this Privacy Policy.'],
  ['2. Information We Collect', 'Account Information: When you create an account, we may collect your name if provided, email address, and authentication provider information from Email/Password or Google Sign-In.\n\nProductivity Data: Priora stores information you create and manage within the application, including tasks, goals, milestones, schedules, reminders, focus sessions, notes, and related productivity records.\n\nUploaded Files and Attachments: You may upload images (JPG, PNG, WEBP, GIF) and documents (PDF, DOCX, TXT, MD). These files are stored and associated with your account to provide core application functionality.\n\nProfile Information: Priora may store profile avatar images, avatar URLs provided through Google Sign-In, and avatar URLs manually configured by users.'],
  ['3. How We Use Information', 'We use collected information to create and manage user accounts, authenticate and secure access to Priora, provide task management and productivity features, deliver reminders and scheduled notifications, calculate personal productivity insights and statistics, maintain and improve service reliability, respond to support requests, and protect the security and integrity of the platform.'],
  ['4. Productivity Analytics', 'Priora generates personal productivity insights using information already stored within your account. These may include task completion statistics, productivity streaks, goal completion rates, focus session summaries, and personal productivity trends. These analytics are generated solely from your own data and are intended to help you better understand and improve your productivity. Priora does not sell, rent, or share these analytics for advertising purposes.'],
  ['5. Notifications and Reminders', 'Priora may deliver local device notifications, including task reminders, deadline alerts, morning summaries, focus session notifications, and scheduled productivity reminders. These notifications are part of the core functionality of the application.'],
  ['6. Authentication', 'Priora supports Email and Password authentication and Google Sign-In. User passwords are protected using secure industry-standard hashing mechanisms and are never stored in plain text. When using Google Sign-In, Priora receives only the information necessary to authenticate and create your account.'],
  ['7. Permissions', 'Depending on device and operating system requirements, Priora may request Internet access, network state access, notification permissions, exact alarm scheduling permissions, device restart handling for reminder restoration, vibration for reminders and alarms, and battery optimization exemptions to improve reminder reliability. Priora does not request access to device contacts, microphone, GPS or location services, or camera hardware, except where future features explicitly require such permissions and are separately disclosed.'],
  ['8. Third-Party Services', 'Priora uses Supabase to provide authentication, database storage, and related backend infrastructure services. When users choose Google authentication, Google processes authentication requests in accordance with Google\'s own privacy policies. Priora may also use cloud hosting, networking, storage, and infrastructure providers necessary to operate and maintain the service. These providers process information only as required to deliver Priora\'s services.'],
  ['9. Data Sharing', 'Priora does not sell personal information and does not share personal information with advertisers, marketing networks, or data brokers. Information may be disclosed only when necessary to provide and maintain the service, process authentication and account management, comply with applicable laws, protect the security, safety, and integrity of Priora, or investigate fraud, abuse, or security incidents.'],
  ['10. Data Security', 'We implement reasonable technical and organizational safeguards designed to protect user information from unauthorized access, disclosure, alteration, or destruction. While we strive to protect user data, no method of electronic transmission or storage can be guaranteed to be completely secure.'],
  ['11. Data Retention', 'We retain user information only for as long as necessary to provide requested services, maintain account functionality, comply with legal obligations, resolve disputes, and enforce agreements. Retention periods may vary depending on the type of information involved.'],
  ['12. Account Deletion and Data Removal', 'Users may request deletion of their account and associated data by contacting priorahq@gmail.com. Upon successful verification of account ownership, we will make reasonable efforts to delete account information and associated productivity data, subject to legal, security, operational, or regulatory requirements. Certain records may be retained when required by law or necessary for legitimate business and security purposes.'],
  ["13. Children's Privacy", 'Priora is not intended for children under the age required by applicable law to independently create and manage online accounts without parental consent. If we become aware that information has been collected in violation of applicable law, we will take reasonable steps to remove such information.'],
  ['14. Your Rights', 'Depending on your jurisdiction and applicable laws, you may have rights to access your personal information, correct inaccurate information, request deletion of personal information, and request information regarding data processing. Requests may be submitted using the contact information provided below.'],
  ['15. International Access', 'Priora is operated from India. Users accessing the service from other jurisdictions do so voluntarily and are responsible for compliance with applicable local laws and regulations.'],
  ['16. Changes to This Privacy Policy', 'We may update this Privacy Policy from time to time. Any changes will be posted on this page with an updated Last Updated date. Continued use of Priora after changes become effective constitutes acceptance of the revised Privacy Policy.'],
]

export default function PrioraPrivacyPolicy() {
  return <main><section className="directory-header policy-header"><div className="container"><span className="badge">Priora / Legal</span><h1>Privacy policy for Priora.</h1><p>Effective September 3, 2026 · Last updated September 3, 2026</p></div></section><section className="section compact-section policy-content"><div className="container narrow"><p className="policy-lead">Welcome to Priora. Your privacy is important to us. This Privacy Policy explains what information we collect, how we use it, how we protect it, and the choices available to you when using Priora.</p>{sections.map(([title, body]) => <section className="policy-block" key={title}><h2>{title}</h2>{body.split('\n\n').map(paragraph => <p key={paragraph}>{paragraph}</p>)}</section>)}<section className="policy-block"><h2>17. Contact Us</h2><p>If you have questions regarding this Privacy Policy, data practices, or privacy-related requests, please contact <a className="policy-link" href="mailto:priorahq@gmail.com">priorahq@gmail.com <ArrowUpRight size={14} /></a>.</p><p>Website: <a className="policy-link" href="https://priorapp.co.in/">priorapp.co.in <ArrowUpRight size={14} /></a></p><p>Privacy Policy URL: <a className="policy-link" href="https://priorapp.co.in/privacy/priora">priorapp.co.in/privacy/priora <ArrowUpRight size={14} /></a></p></section></div></section></main>
}
